# Generated by Django 3.0.3 on 2020-03-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='header',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
